# Generated by Django 4.0.4 on 2022-05-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
