# Generated by Django 4.0.4 on 2022-05-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_task_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id_user',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tms.user'),
            preserve_default=False,
        ),
    ]
