# Generated by Django 4.0.4 on 2022-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_remove_task_id_user_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.AddField(
            model_name='task',
            name='status_task',
            field=models.CharField(default='planned', max_length=30),
            preserve_default=False,
        ),
    ]
